angular.module('todoApp', []).controller 'TodoListController', ->
  todoList = this
  todoList.todos = [
    {
      text: 'learn AngularJS'
      done: false
    }
    {
      text: 'build an Angular application'
      done: false
    }
  ]

  todoList.add = ->
    todoList.todos.push
      text: todoList.todoText
      done: false
    todoList.todoText = ''
    return

  todoList.remaining = ->
    count = 0
    angular.forEach todoList.todos, (todo) ->
      count += if todo.done then 0 else 1
      return
    count

  todoList.archive = ->
    old = todoList.todos
    todoList.todos = []
    angular.forEach old, (todo) ->
      if !todo.done
        todoList.todos.push todo
      return
    return

  return

# ---
# generated by js2coffee 2.2.0